name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
        #os: [macos-latest, ubuntu-latest, windows-latest]
        #node: [10, 12, 14]
        #exclude:
        #  - os: macos-latest
        #    node: 10
        
    steps:
      - name: my first step
        env: 
          MY_VAR: Hi there! my name is
          FIRST_NAME: Gil
          LAST_NAME: Shvarzman
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
